name: TechTrends - Package with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Output Run Number
        run: echo ${{ github.run_number }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            luizvellozo/techtrends
          tags: |
            type=ref,event=branch,suffix=-${{github.run_number}}
            type=ref,event=pr,suffix=-${{github.run_number}}
            type=semver,pattern={{version}},suffix=-${{github.run_number}}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{github.run_number}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./project
          file: ./project/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
